destination: ./site

baseurl: /phila-dashboards

# For running locally the path string should be empty.
# path:


# Update this with your client ID.
# https://developers.google.com/analytics/devguides/reporting/embed/v1/devguide#client-id
client_id: 105615440679-9nda6c33lljuin6tn7g08er3r7lmimah.apps.googleusercontent.com

# 105615440679-1qifvu02lj19d2f3nc0es6lu9lne1urn.apps.googleusercontent.com

# In Google Developers Console, project name is 
# phila-dashboards
